# Generated by Django 3.2.14 on 2022-07-17 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='picture',
            new_name='picture_intro',
        ),
    ]
