# Generated by Django 3.2.12 on 2022-04-15 12:26

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningpost',
            name='introduction',
            field=tinymce.models.HTMLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='introduction',
            field=tinymce.models.HTMLField(default=''),
            preserve_default=False,
        ),
    ]
