# Generated by Django 3.2.12 on 2022-04-22 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20220415_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='seo_tag',
        ),
        migrations.RemoveField(
            model_name='service',
            name='seo_tag',
        ),
    ]
