# Generated by Django 3.2.14 on 2022-07-17 14:51

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('store', '0003_alter_service_picture_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='picture_descrip',
            field=filer.fields.image.FilerImageField(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='service_descrip', to=settings.FILER_IMAGE_MODEL),
            preserve_default=False,
        ),
    ]
