# Generated by Django 3.2.12 on 2022-05-25 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20220422_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningpost',
            name='tags',
        ),
    ]
