# Generated by Django 3.2.12 on 2022-03-31 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_orderitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'initial'), (2, 'processing'), (3, 'confirmed')], default=2, verbose_name='status'),
        ),
    ]
