# Generated by Django 3.2.12 on 2022-05-26 13:20

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_learningpost_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningpost',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='learningpost',
            name='introduction',
            field=models.TextField(max_length=500),
        ),
    ]
