# Generated by Django 3.2.12 on 2022-05-26 14:42

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20220526_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningpost',
            name='introduction',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
