# Generated by Django 3.2.12 on 2022-05-26 14:46

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('store', '0007_alter_learningpost_introduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='picture2',
            field=filer.fields.image.FilerImageField(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='event', to=settings.FILER_IMAGE_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='learningpost',
            name='picture2',
            field=filer.fields.image.FilerImageField(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='learning_post', to=settings.FILER_IMAGE_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='picture2',
            field=filer.fields.image.FilerImageField(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='service', to=settings.FILER_IMAGE_MODEL),
            preserve_default=False,
        ),
    ]
