# Generated by Django 3.2.12 on 2022-05-26 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20220526_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='learningpost',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='service',
            name='picture',
        ),
    ]
