# Generated by Django 3.2.12 on 2022-05-31 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20220526_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='show_in_home',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='learningpost',
            name='show_big_in_home',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='learningpost',
            name='show_in_home',
            field=models.BooleanField(default=False),
        ),
    ]
