# Generated by Django 3.2.12 on 2022-06-01 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20220531_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='policy',
        ),
    ]
