# Generated by Django 3.2.12 on 2022-06-03 08:06

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_remove_event_policy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learningpost',
            old_name='show_big_in_home',
            new_name='highlight_in_home',
        ),
        migrations.RemoveField(
            model_name='event',
            name='organizer_mobile_number',
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='introduction',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
