# Generated by Django 3.2.12 on 2022-06-03 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20220603_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningpost',
            name='highlight_in_home',
        ),
        migrations.AddField(
            model_name='service',
            name='highlight_in_home',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='show_in_home',
            field=models.BooleanField(default=False),
        ),
    ]
