# Generated by Django 3.2.12 on 2022-06-03 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_auto_20220603_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='introduction',
            field=models.TextField(),
        ),
    ]
