# Generated by Django 3.2.12 on 2022-04-08 13:39

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_event_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='organizer_mobile_number',
            field=models.CharField(default='00989354356804', max_length=20, verbose_name='mobile'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.DeleteModel(
            name='Organizer',
        ),
    ]
