# Generated by Django 3.2.12 on 2022-04-09 06:05

import datetime
from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_auto_20220408_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=django_jalali.db.models.jDateTimeField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='pub_date',
            field=django_jalali.db.models.jDateTimeField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=django_jalali.db.models.jDateTimeField(),
        ),
    ]
