# Generated by Django 3.2.12 on 2022-04-09 06:39

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_auto_20220409_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=django_jalali.db.models.jDateTimeField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='pub_date',
            field=django_jalali.db.models.jDateTimeField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=django_jalali.db.models.jDateTimeField(),
        ),
    ]
