# Generated by Django 3.2.12 on 2022-03-31 12:02

import django.core.files.storage
from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_alter_post_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='attachment',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/attachment/', location=pathlib.PurePosixPath('/home/saeid/arad/learning_attachments')), upload_to=''),
        ),
    ]
