# Generated by Django 3.2.14 on 2022-10-05 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='seo_tag',
            field=models.TextField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
