# Generated by Django 3.2.12 on 2022-04-02 09:34

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='intro',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=''),
            preserve_default=False,
        ),
    ]
