# Generated by Django 3.2.12 on 2022-05-24 12:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content3',
            field=ckeditor.fields.RichTextField(default=''),
            preserve_default=False,
        ),
    ]
