# Generated by Django 3.2.12 on 2022-05-24 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_content3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='intro',
        ),
    ]
