# Generated by Django 3.2.12 on 2022-05-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20220525_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='intro',
            field=models.TextField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
