# Generated by Django 3.2.12 on 2022-05-25 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_post_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='show_in_home',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='intro',
            field=models.TextField(max_length=500),
        ),
    ]
