# Generated by Django 3.2.13 on 2022-06-09 06:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mobile',
            field=models.CharField(default='09123456789', max_length=20, validators=[django.core.validators.RegexValidator(message='شماره موبایل معتبر نیست', regex='^(?=.{11})09')], verbose_name='mobile'),
            preserve_default=False,
        ),
    ]
