# Generated by Django 3.2.12 on 2022-05-25 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_picture',
        ),
    ]
