# Generated by Django 3.2.14 on 2022-07-17 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='final_description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='language_exam_description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='preference_to_join',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
