# Generated by Django 3.2.13 on 2022-06-07 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='education_status',
            field=models.CharField(choices=[('high_school', 'High school'), ('diploma', 'Diploma'), ('associate_degree', 'Associate Degree'), ("bachelor's_degree", "Bachelor's degree"), ("master's_degree", "Master's degree"), ('p.h.d', 'P.H.D')], max_length=50),
        ),
    ]
