# Generated by Django 3.2.13 on 2022-06-07 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0002_alter_message_education_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='marital_status',
            field=models.CharField(choices=[('single', 'Single'), ('married', 'Married')], max_length=50),
        ),
    ]
